access_token = ''
bonsai_url = 'http://elastic:eiw3Hoo1@albert.lundstig.com'
file_index = 'file'
interface_index = 'interface'
class_index = 'class'
enum_index = 'enum'
method_index = 'method'
variable_index = 'variable'
